# https://kubernetes.io/ja/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: original-covid-app-japan-backend-service
  labels:
    app: original-covid-app-japan-backend
spec:
  type: LoadBalancer
  ports:
  - name: backend-port
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: original-covid-app-japan-backend-pod
