# ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: original-covid-app-japan-frontend-deployment
  labels:
    app: original-covid-app-japan-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: original-covid-app-japan-frontend-pod
  template:
    metadata:
      labels:
        app: original-covid-app-japan-frontend-pod
    spec:
      containers:
      - name: original-covid-app-japan-frontend
        image: watanabe61/original-covid-app-japan-frontend:latest
        ports:
        - containerPort: 80