# https://kubernetes.io/ja/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: original-covid-app-world-service
  labels:
    app: original-covid-app-world
spec:
  selector:
    app: original-covid-app-world-pod
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP