# https://kubernetes.io/ja/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: original-covid-app-japan-backend-service
  labels:
    app: original-covid-app-japan-backend
spec:
  selector:
    app: original-covid-app-japan-backend-pod
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  
